import { createHash } from 'node:crypto';

import {
  FieldValue,
  Timestamp,
  type DocumentReference,
  type DocumentData,
} from 'firebase-admin/firestore';
import { onDocumentCreated } from 'firebase-functions/v2/firestore';
import { onDocumentWritten } from 'firebase-functions/v2/firestore';
import { onSchedule } from 'firebase-functions/v2/scheduler';

import {
  APP_REGION,
  APP_TIMEZONE,
  EVENT_REMINDER_GRACE_MINUTES,
  EVENT_REMINDER_JOB_SCHEDULE,
  EVENT_REMINDER_LOOKAHEAD_MINUTES,
  EVENT_REMINDER_SCAN_LIMIT,
  NOTIFICATION_EVENT_MAX_AUDIENCE,
} from '../config/runtime';
import { db } from '../shared/firestore';
import {
  notifyMembers,
  resolveAudienceMemberIdsByEventScope,
} from '../notifications/push-delivery';
import { logInfo, logWarn } from '../shared/logger';

type EventRecord = {
  clanId?: string | null;
  branchId?: string | null;
  title?: string | null;
  description?: string | null;
  eventType?: string | null;
  ritualKey?: string | null;
  isAutoGenerated?: boolean | null;
  isRecurring?: boolean | null;
  recurrenceRule?: string | null;
  reminderOffsetsMinutes?: unknown;
  startsAt?: unknown;
  status?: string | null;
  visibility?: string | null;
  nextReminderAt?: unknown;
  nextReminderOffsetMinutes?: unknown;
  nextReminderOccurrenceStartsAt?: unknown;
  reminderCursorVersion?: unknown;
  reminderCursorUpdatedAt?: unknown;
  reminderCursorSource?: string | null;
};

type EventReminderRunInput = {
  source: string;
  now?: Date;
};

type EventReminderRunResult = {
  scanned: number;
  candidates: number;
  remindersDue: number;
  remindersSent: number;
  skippedNoAudience: number;
  skippedDeduplicated: number;
  skippedInvalidEvent: number;
  truncatedUpcomingQuery: boolean;
  truncatedRecurringQuery: boolean;
};

type ReminderPointer = {
  reminderAt: Date;
  offsetMinutes: number;
  occurrenceStartsAt: Date;
};

const eventsCollection = db.collection('events');
const eventReminderDispatchesCollection = db.collection('eventReminderDispatches');
const EVENT_REMINDER_CURSOR_VERSION = 1;
const reminderDateTimeFormatterEn = new Intl.DateTimeFormat('en-GB', {
  dateStyle: 'short',
  timeStyle: 'short',
  hour12: false,
  timeZone: APP_TIMEZONE,
});
const reminderDateTimeFormatterVi = new Intl.DateTimeFormat('vi-VN', {
  dateStyle: 'short',
  timeStyle: 'short',
  hour12: false,
  timeZone: APP_TIMEZONE,
});

export const onEventCreated = onDocumentCreated(
  {
    document: 'events/{eventId}',
    region: APP_REGION,
  },
  async (event) => {
    const snapshot = event.data;
    if (!snapshot) {
      logWarn('event create trigger received no snapshot', {
        eventId: event.params.eventId,
      });
      return;
    }

    const data = snapshot.data() as EventRecord;
    if (data.isAutoGenerated === true) {
      logInfo('skip notifications for auto-generated event', {
        eventId: event.params.eventId,
        ritualKey: data.ritualKey ?? null,
      });
      return;
    }

    const clanId = normalizeString(data.clanId);
    if (clanId.length === 0) {
      logWarn('event created without clanId', {
        eventId: event.params.eventId,
      });
      return;
    }

    const visibility = normalizeVisibility(data.visibility);
    const audienceMemberIds = await resolveAudienceMemberIdsByEventScope({
      clanId,
      branchId: normalizeNullableString(data.branchId),
      visibility,
      maxAudience: NOTIFICATION_EVENT_MAX_AUDIENCE,
    });
    if (audienceMemberIds.length === 0) {
      logInfo('event created with no eligible notification audience', {
        eventId: event.params.eventId,
        clanId,
        visibility,
      });
      return;
    }

    const createdContent = buildEventCreatedContent({
      title: data.title,
      description: data.description,
    });
    const delivery = await notifyMembers({
      clanId,
      memberIds: audienceMemberIds,
      type: 'event_created',
      title: createdContent.vi.title,
      body: createdContent.vi.body,
      localized: createdContent,
      target: 'event',
      targetId: event.params.eventId,
      extraData: {
        eventId: event.params.eventId,
        visibility,
      },
    });

    logInfo('event created', {
      eventId: event.params.eventId,
      clanId,
      eventType: data.eventType ?? null,
      startsAt: data.startsAt ?? null,
      visibility,
      ...delivery,
    });
  },
);

export const sendEventReminder = onSchedule(
  {
    schedule: EVENT_REMINDER_JOB_SCHEDULE,
    region: APP_REGION,
    timeZone: APP_TIMEZONE,
    maxInstances: 1,
  },
  async () => {
    const result = await sendEventReminderRun({
      source: 'function:sendEventReminder',
    });
    logInfo('sendEventReminder tick', result);
  },
);

export const syncEventReminderCursor = onDocumentWritten(
  {
    document: 'events/{eventId}',
    region: APP_REGION,
    maxInstances: 1,
  },
  async (event) => {
    const snapshot = event.data?.after;
    if (!snapshot?.exists) {
      return;
    }
    const data = snapshot.data() as EventRecord;
    const now = new Date();
    const reminderWindowStart = new Date(
      now.getTime() - (Math.max(5, EVENT_REMINDER_GRACE_MINUTES) * 60 * 1000),
    );
    await syncReminderCursorForEvent({
      eventId: snapshot.id,
      eventRef: snapshot.ref,
      data,
      baseline: reminderWindowStart,
      source: 'trigger:syncEventReminderCursor',
    });
  },
);

export async function sendEventReminderRun(
  input: EventReminderRunInput,
): Promise<EventReminderRunResult> {
  const now = input.now ?? new Date();
  const reminderWindowStart = new Date(
    now.getTime() - (Math.max(5, EVENT_REMINDER_GRACE_MINUTES) * 60 * 1000),
  );
  const lookAheadEnd = new Date(
    now.getTime() + (Math.max(60, EVENT_REMINDER_LOOKAHEAD_MINUTES) * 60 * 1000),
  );
  const safeScanLimit = Math.max(100, EVENT_REMINDER_SCAN_LIMIT);
  const cursorBackfillLimit = Math.min(300, safeScanLimit);

  const [dueSnapshot, cursorBackfillSnapshot] = await Promise.all([
    eventsCollection
      .where('nextReminderAt', '>=', Timestamp.fromDate(reminderWindowStart))
      .where('nextReminderAt', '<=', Timestamp.fromDate(now))
      .orderBy('nextReminderAt', 'asc')
      .limit(safeScanLimit)
      .get(),
    eventsCollection
      .where('reminderCursorVersion', '==', null)
      .limit(cursorBackfillLimit)
      .get(),
  ]);

  const eventDocsById = new Map<string, {
    data: EventRecord;
    ref: DocumentReference<DocumentData>;
  }>();
  for (const doc of [...dueSnapshot.docs, ...cursorBackfillSnapshot.docs]) {
    eventDocsById.set(doc.id, {
      data: doc.data() as EventRecord,
      ref: doc.ref,
    });
  }

  let candidates = 0;
  let remindersDue = 0;
  let remindersSent = 0;
  let skippedNoAudience = 0;
  let skippedDeduplicated = 0;
  let skippedInvalidEvent = 0;

  for (const [eventId, entry] of eventDocsById.entries()) {
    const data = entry.data;
    if (!isEventStatusEligible(data.status)) {
      await syncReminderCursorForEvent({
        eventId,
        eventRef: entry.ref,
        data,
        baseline: now,
        source: input.source,
      });
      continue;
    }

    const clanId = normalizeString(data.clanId);
    if (clanId.length === 0) {
      skippedInvalidEvent += 1;
      continue;
    }

    const startsAt = toDate(data.startsAt);
    if (startsAt == null) {
      skippedInvalidEvent += 1;
      continue;
    }

    const reminderOffsets = normalizeReminderOffsets(data.reminderOffsetsMinutes);
    if (reminderOffsets.length === 0) {
      await syncReminderCursorForEvent({
        eventId,
        eventRef: entry.ref,
        data,
        baseline: now,
        source: input.source,
      });
      continue;
    }
    candidates += 1;

    const dueReminders = resolveDueRemindersForWindow({
      startsAt,
      recurrenceRule: data.recurrenceRule,
      isRecurring: data.isRecurring === true,
      offsets: reminderOffsets,
      windowStart: reminderWindowStart,
      now,
    }).filter((reminder) => reminder.occurrenceStartsAt.getTime() <= lookAheadEnd.getTime());

    for (const reminder of dueReminders) {
      const offsetMinutes = reminder.offsetMinutes;
      const reminderAt = reminder.reminderAt;
      const occurrenceStartsAt = reminder.occurrenceStartsAt;
      remindersDue += 1;

      const reminderDispatchId = buildReminderDispatchId({
        eventId,
        reminderAt,
        offsetMinutes,
      });
      const dispatchRef = eventReminderDispatchesCollection.doc(reminderDispatchId);
      try {
        await dispatchRef.create({
          id: reminderDispatchId,
          eventId,
          clanId,
          reminderOffsetMinutes: offsetMinutes,
          reminderAt: Timestamp.fromDate(reminderAt),
          occurrenceStartsAt: Timestamp.fromDate(occurrenceStartsAt),
          status: 'processing',
          source: input.source,
          createdAt: FieldValue.serverTimestamp(),
          updatedAt: FieldValue.serverTimestamp(),
        });
      } catch (error) {
        if (isAlreadyExistsFirestoreError(error)) {
          skippedDeduplicated += 1;
          continue;
        }
        throw error;
      }

      const visibility = normalizeVisibility(data.visibility);
      const audienceMemberIds = await resolveAudienceMemberIdsByEventScope({
        clanId,
        branchId: normalizeNullableString(data.branchId),
        visibility,
        maxAudience: NOTIFICATION_EVENT_MAX_AUDIENCE,
      });
      if (audienceMemberIds.length === 0) {
        skippedNoAudience += 1;
        await dispatchRef.set(
          {
            status: 'skipped_no_audience',
            updatedAt: FieldValue.serverTimestamp(),
          },
          { merge: true },
        );
        continue;
      }

      try {
        const reminderContent = buildReminderContent({
          title: data.title,
          startsAt: occurrenceStartsAt,
          offsetMinutes,
        });
        await notifyMembers({
          clanId,
          memberIds: audienceMemberIds,
          type: 'event_reminder',
          title: reminderContent.vi.title,
          body: reminderContent.vi.body,
          localized: reminderContent,
          target: 'event',
          targetId: eventId,
          extraData: {
            eventId,
            reminderOffsetMinutes: `${offsetMinutes}`,
            reminderAtMs: `${reminderAt.getTime()}`,
          },
        });
        remindersSent += 1;
        await dispatchRef.set(
          {
            status: 'sent',
            sentAt: FieldValue.serverTimestamp(),
            updatedAt: FieldValue.serverTimestamp(),
          },
          { merge: true },
        );
      } catch (error) {
        logWarn('event reminder delivery failed', {
          eventId,
          clanId,
          offsetMinutes,
          reminderAt: reminderAt.toISOString(),
          error: `${error}`,
        });
        await dispatchRef.delete().catch(() => undefined);
      }
    }

    await syncReminderCursorForEvent({
      eventId,
      eventRef: entry.ref,
      data,
      baseline: now,
      source: input.source,
    });
  }

  return {
    scanned: eventDocsById.size,
    candidates,
    remindersDue,
    remindersSent,
    skippedNoAudience,
    skippedDeduplicated,
    skippedInvalidEvent,
    truncatedUpcomingQuery: dueSnapshot.size >= safeScanLimit,
    truncatedRecurringQuery: cursorBackfillSnapshot.size >= cursorBackfillLimit,
  };
}

async function syncReminderCursorForEvent(input: {
  eventId: string;
  eventRef: DocumentReference<DocumentData>;
  data: EventRecord;
  baseline: Date;
  source: string;
}): Promise<void> {
  const startsAt = toDate(input.data.startsAt);
  const reminderOffsets = normalizeReminderOffsets(input.data.reminderOffsetsMinutes);
  const pointer = resolveNextReminderPointer({
    startsAt,
    recurrenceRule: input.data.recurrenceRule,
    isRecurring: input.data.isRecurring === true,
    offsets: reminderOffsets,
    baseline: input.baseline,
  });

  const currentPointer = resolveCurrentReminderPointer(input.data);
  const currentVersion = parseInteger(input.data.reminderCursorVersion);
  if (
    currentVersion === EVENT_REMINDER_CURSOR_VERSION &&
    pointersEqual(currentPointer, pointer)
  ) {
    return;
  }

  await input.eventRef.set({
    nextReminderAt: pointer == null ? null : Timestamp.fromDate(pointer.reminderAt),
    nextReminderOffsetMinutes: pointer?.offsetMinutes ?? null,
    nextReminderOccurrenceStartsAt:
      pointer == null ? null : Timestamp.fromDate(pointer.occurrenceStartsAt),
    reminderCursorVersion: EVENT_REMINDER_CURSOR_VERSION,
    reminderCursorUpdatedAt: FieldValue.serverTimestamp(),
    reminderCursorSource: input.source,
    updatedAt: FieldValue.serverTimestamp(),
  }, { merge: true });
}

function resolveDueRemindersForWindow(input: {
  startsAt: Date;
  recurrenceRule: string | null | undefined;
  isRecurring: boolean;
  offsets: Array<number>;
  windowStart: Date;
  now: Date;
}): Array<ReminderPointer> {
  const occurrenceStartsAt = resolveReminderOccurrenceStart({
    startsAt: input.startsAt,
    recurrenceRule: input.recurrenceRule,
    isRecurring: input.isRecurring,
    now: input.now,
  });
  if (occurrenceStartsAt == null) {
    return [];
  }

  const due: Array<ReminderPointer> = [];
  for (const offsetMinutes of input.offsets) {
    const reminderAt = new Date(
      occurrenceStartsAt.getTime() - (offsetMinutes * 60 * 1000),
    );
    if (
      reminderAt.getTime() < input.windowStart.getTime() ||
      reminderAt.getTime() > input.now.getTime()
    ) {
      continue;
    }
    due.push({
      reminderAt,
      offsetMinutes,
      occurrenceStartsAt,
    });
  }
  due.sort((left, right) => left.reminderAt.getTime() - right.reminderAt.getTime());
  return due;
}

function resolveNextReminderPointer(input: {
  startsAt: Date | null;
  recurrenceRule: string | null | undefined;
  isRecurring: boolean;
  offsets: Array<number>;
  baseline: Date;
}): ReminderPointer | null {
  if (input.startsAt == null || input.offsets.length === 0) {
    return null;
  }
  if (!input.isRecurring) {
    return resolveNextPointerForOccurrence(
      input.startsAt,
      input.offsets,
      input.baseline,
    );
  }

  const recurrenceRule = normalizeString(input.recurrenceRule).toUpperCase();
  if (!recurrenceRule.includes('FREQ=YEARLY')) {
    return resolveNextPointerForOccurrence(
      input.startsAt,
      input.offsets,
      input.baseline,
    );
  }

  const maxOffsetMinutes = Math.max(...input.offsets);
  const shiftedBaseline = new Date(
    input.baseline.getTime() + (maxOffsetMinutes * 60 * 1000),
  );
  let candidateOccurrence = resolveYearlyOccurrenceAtOrAfter(
    input.startsAt,
    shiftedBaseline,
  );

  for (let index = 0; index < 3; index += 1) {
    const pointer = resolveNextPointerForOccurrence(
      candidateOccurrence,
      input.offsets,
      input.baseline,
    );
    if (pointer != null) {
      return pointer;
    }
    candidateOccurrence = addYearsSafely(candidateOccurrence, 1);
  }
  return null;
}

function resolveNextPointerForOccurrence(
  occurrenceStartsAt: Date,
  offsets: Array<number>,
  baseline: Date,
): ReminderPointer | null {
  let pointer: ReminderPointer | null = null;
  for (const offsetMinutes of offsets) {
    const reminderAt = new Date(
      occurrenceStartsAt.getTime() - (offsetMinutes * 60 * 1000),
    );
    if (reminderAt.getTime() < baseline.getTime()) {
      continue;
    }
    if (pointer == null || reminderAt.getTime() < pointer.reminderAt.getTime()) {
      pointer = {
        reminderAt,
        offsetMinutes,
        occurrenceStartsAt,
      };
    }
  }
  return pointer;
}

function resolveYearlyOccurrenceAtOrAfter(startsAt: Date, now: Date): Date {
  const candidate = new Date(Date.UTC(
    now.getUTCFullYear(),
    startsAt.getUTCMonth(),
    startsAt.getUTCDate(),
    startsAt.getUTCHours(),
    startsAt.getUTCMinutes(),
    startsAt.getUTCSeconds(),
    startsAt.getUTCMilliseconds(),
  ));
  if (candidate.getTime() < now.getTime()) {
    candidate.setUTCFullYear(candidate.getUTCFullYear() + 1);
  }
  return candidate;
}

function addYearsSafely(value: Date, years: number): Date {
  const candidate = new Date(value.getTime());
  candidate.setUTCFullYear(candidate.getUTCFullYear() + years);
  return candidate;
}

function resolveCurrentReminderPointer(data: EventRecord): ReminderPointer | null {
  const reminderAt = toDate(data.nextReminderAt);
  if (reminderAt == null) {
    return null;
  }
  const occurrenceStartsAt = toDate(data.nextReminderOccurrenceStartsAt);
  if (occurrenceStartsAt == null) {
    return null;
  }
  const offsetMinutes = parseInteger(data.nextReminderOffsetMinutes);
  if (offsetMinutes == null || offsetMinutes <= 0) {
    return null;
  }
  return {
    reminderAt,
    offsetMinutes,
    occurrenceStartsAt,
  };
}

function pointersEqual(
  left: ReminderPointer | null,
  right: ReminderPointer | null,
): boolean {
  if (left == null || right == null) {
    return left == null && right == null;
  }
  return left.offsetMinutes === right.offsetMinutes &&
    left.reminderAt.getTime() === right.reminderAt.getTime() &&
    left.occurrenceStartsAt.getTime() === right.occurrenceStartsAt.getTime();
}

function parseInteger(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Math.trunc(value);
  }
  if (typeof value === 'string') {
    const parsed = Number.parseInt(value.trim(), 10);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}

function resolveReminderOccurrenceStart(input: {
  startsAt: Date;
  recurrenceRule: string | null | undefined;
  isRecurring: boolean;
  now: Date;
}): Date | null {
  const isYearlyRecurring = input.isRecurring &&
    normalizeString(input.recurrenceRule).toUpperCase().includes('FREQ=YEARLY');
  if (!isYearlyRecurring) {
    return input.startsAt;
  }
  return resolveYearlyOccurrenceAtOrAfter(input.startsAt, input.now);
}

function isEventStatusEligible(value: string | null | undefined): boolean {
  const status = normalizeString(value).toLowerCase();
  if (status.length === 0) {
    return true;
  }
  return ![
    'cancelled',
    'canceled',
    'completed',
    'archived',
    'deleted',
    'inactive',
    'draft',
  ].includes(status);
}

function normalizeReminderOffsets(value: unknown): Array<number> {
  if (!Array.isArray(value)) {
    return [];
  }
  return [...new Set(
    value
      .map((entry) => {
        if (typeof entry === 'number' && Number.isFinite(entry)) {
          return Math.trunc(entry);
        }
        if (typeof entry === 'string') {
          const parsed = Number.parseInt(entry, 10);
          return Number.isFinite(parsed) ? parsed : null;
        }
        return null;
      })
      .filter((entry): entry is number => entry != null && entry > 0)
      .filter((entry) => entry <= EVENT_REMINDER_LOOKAHEAD_MINUTES),
  )].sort((left, right) => right - left);
}

function buildReminderDispatchId(input: {
  eventId: string;
  reminderAt: Date;
  offsetMinutes: number;
}): string {
  const fingerprint = createHash('sha256')
    .update(
      `${input.eventId}:${input.reminderAt.toISOString()}:${input.offsetMinutes}`,
    )
    .digest('hex')
    .slice(0, 32);
  return `evt_reminder_${fingerprint}`;
}

function isAlreadyExistsFirestoreError(error: unknown): boolean {
  const code = (error as { code?: unknown })?.code;
  if (code === 6 || code === 'already-exists' || code === 'ALREADY_EXISTS') {
    return true;
  }
  const message = `${error ?? ''}`.toLowerCase();
  return message.includes('already exists');
}

function buildEventCreatedContent(input: {
  title: string | null | undefined;
  description: string | null | undefined;
}): {
  vi: { title: string; body: string };
  en: { title: string; body: string };
} {
  const trimmedTitle = normalizeString(input.title);
  const trimmedDescription = normalizeString(input.description);
  return {
    vi: {
      title: trimmedTitle.length > 0 ? trimmedTitle : 'Sự kiện gia phả',
      body: trimmedDescription.length > 0
        ? trimmedDescription
        : 'Mở BeFam để xem chi tiết và lời nhắc sự kiện.',
    },
    en: {
      title: trimmedTitle.length > 0 ? trimmedTitle : 'Family event',
      body: trimmedDescription.length > 0
        ? trimmedDescription
        : 'Open BeFam to view event details and reminders.',
    },
  };
}

function buildReminderContent(input: {
  title: string | null | undefined;
  startsAt: Date;
  offsetMinutes: number;
}): {
  vi: { title: string; body: string };
  en: { title: string; body: string };
} {
  const baseTitle = normalizeString(input.title);
  const viTitle = baseTitle.length > 0 ? baseTitle : 'Sự kiện gia phả';
  const enTitle = baseTitle.length > 0 ? baseTitle : 'Family event';
  const startsAtLabelVi = reminderDateTimeFormatterVi.format(input.startsAt);
  const startsAtLabelEn = reminderDateTimeFormatterEn.format(input.startsAt);
  return {
    vi: {
      title: `Nhắc lịch: ${viTitle}`,
      body:
        `Bắt đầu lúc ${startsAtLabelVi} (${formatOffsetLabel(input.offsetMinutes, 'vi')} trước).`,
    },
    en: {
      title: `Reminder: ${enTitle}`,
      body:
        `Starts at ${startsAtLabelEn} (${formatOffsetLabel(input.offsetMinutes, 'en')} before).`,
    },
  };
}

function formatOffsetLabel(
  offsetMinutes: number,
  languageCode: 'vi' | 'en',
): string {
  if (offsetMinutes % 1440 === 0) {
    const days = Math.trunc(offsetMinutes / 1440);
    if (languageCode === 'vi') {
      return `${days} ngày`;
    }
    return `${days} day${days === 1 ? '' : 's'}`;
  }
  if (offsetMinutes % 60 === 0) {
    const hours = Math.trunc(offsetMinutes / 60);
    if (languageCode === 'vi') {
      return `${hours} giờ`;
    }
    return `${hours} hour${hours === 1 ? '' : 's'}`;
  }
  if (languageCode === 'vi') {
    return `${offsetMinutes} phút`;
  }
  return `${offsetMinutes} minute${offsetMinutes === 1 ? '' : 's'}`;
}

function normalizeVisibility(value: string | null | undefined): string {
  const visibility = normalizeString(value).toLowerCase();
  if (visibility === 'branch') {
    return 'branch';
  }
  return 'clan';
}

function normalizeString(value: unknown): string {
  if (typeof value !== 'string') {
    return '';
  }
  return value.trim();
}

function normalizeNullableString(value: unknown): string | null {
  const normalized = normalizeString(value);
  return normalized.length > 0 ? normalized : null;
}

function toDate(value: unknown): Date | null {
  if (value instanceof Timestamp) {
    return value.toDate();
  }
  if (value instanceof Date) {
    return value;
  }
  if (
    value != null &&
    typeof value === 'object' &&
    'toDate' in value &&
    typeof (value as { toDate?: unknown }).toDate === 'function'
  ) {
    try {
      return (value as { toDate: () => Date }).toDate();
    } catch {
      return null;
    }
  }
  return null;
}

export const __testOnly = {
  normalizeReminderOffsets,
  resolveReminderOccurrenceStart,
  resolveDueRemindersForWindow,
  resolveNextReminderPointer,
  resolveYearlyOccurrenceAtOrAfter,
  buildReminderDispatchId,
};
