import {
  FieldValue,
  Timestamp,
} from 'firebase-admin/firestore';
import { onDocumentWritten } from 'firebase-functions/v2/firestore';

import { APP_REGION, APP_TIMEZONE } from '../config/runtime';
import { db } from '../shared/firestore';
import { logInfo, logWarn } from '../shared/logger';

const eventsCollection = db.collection('events');
const DEFAULT_REMINDER_OFFSETS_MINUTES = [10080, 1440, 120];
const AUTO_RITUAL_PRESET = 'gender_split_49_50';

type MemberRecord = {
  id?: string | null;
  clanId?: string | null;
  branchId?: string | null;
  fullName?: string | null;
  gender?: string | null;
  deathDate?: string | null;
  updatedBy?: string | null;
};

type RitualMilestone = {
  key: string;
  title: string;
  startsAt: Date;
};

export const onMemberDeathDateChanged = onDocumentWritten(
  {
    document: 'members/{memberId}',
    region: APP_REGION,
  },
  async (event) => {
    const change = event.data;
    const afterSnapshot = change?.after;
    if (!afterSnapshot?.exists) {
      return;
    }

    const afterData = (afterSnapshot.data() ?? {}) as MemberRecord;
    const beforeData = (change?.before?.data() ?? null) as MemberRecord | null;

    const deathDate = parseDateOnly(afterData.deathDate);
    if (deathDate == null) {
      return;
    }

    const previousDeathDate = parseDateOnly(beforeData?.deathDate);
    const deathDateChanged =
      previousDeathDate == null ||
      !isSameCalendarDate(previousDeathDate, deathDate);
    if (!deathDateChanged) {
      return;
    }

    const clanId = normalizeString(afterData.clanId);
    const memberId = normalizeString(afterData.id) || normalizeString(event.params.memberId);
    if (clanId.length === 0 || memberId.length === 0) {
      logWarn('skip memorial ritual auto setup due to missing clan/member id', {
        clanId,
        memberId,
      });
      return;
    }

    const actorId = normalizeString(afterData.updatedBy) || 'system:auto_memorial_ritual';
    const fullName = normalizeString(afterData.fullName) || 'Thành viên';
    const branchId = normalizeNullableString(afterData.branchId);
    const milestones = buildRitualMilestones({
      deathDate,
      gender: normalizeNullableString(afterData.gender),
      memberName: fullName,
    });

    const existingSnapshots = await Promise.all(
      milestones.map((milestone) => eventsCollection.doc(eventIdFor(memberId, milestone.key)).get()),
    );
    const batch = db.batch();
    let writeCount = 0;

    for (let index = 0; index < milestones.length; index++) {
      const milestone = milestones[index];
      const eventId = eventIdFor(memberId, milestone.key);
      const eventRef = eventsCollection.doc(eventId);
      const existingSnapshot = existingSnapshots[index];
      const existingData = asRecord(existingSnapshot.data());
      const existingIsAutoGenerated = existingData?.isAutoGenerated === true;
      if (existingSnapshot.exists && !existingIsAutoGenerated) {
        logWarn('skip memorial ritual event update because existing document is manual', {
          eventId,
          memberId,
          clanId,
        });
        continue;
      }

      const startsAt = milestone.startsAt;
      const endsAt = new Date(startsAt.getTime() + 2 * 60 * 60 * 1000);
      const payload: Record<string, unknown> = {
        id: eventId,
        clanId,
        branchId,
        title: milestone.title,
        description: buildDescription({
          milestoneTitle: milestone.title,
          deathDate,
        }),
        eventType: 'death_anniversary',
        targetMemberId: memberId,
        locationName: '',
        locationAddress: '',
        startsAt: Timestamp.fromDate(startsAt),
        endsAt: Timestamp.fromDate(endsAt),
        timezone: APP_TIMEZONE,
        isRecurring: false,
        recurrenceRule: null,
        reminderOffsetsMinutes: DEFAULT_REMINDER_OFFSETS_MINUTES,
        visibility: 'clan',
        status: 'scheduled',
        ritualKey: milestone.key,
        ritualPreset: AUTO_RITUAL_PRESET,
        isAutoGenerated: true,
        autoSource: 'member_death_date',
        deathDateSource: formatDateOnly(deathDate),
        updatedAt: FieldValue.serverTimestamp(),
        updatedBy: actorId,
      };

      if (!existingSnapshot.exists) {
        payload.createdAt = FieldValue.serverTimestamp();
        payload.createdBy = actorId;
      }

      batch.set(eventRef, payload, { merge: true });
      writeCount += 1;
    }

    if (writeCount == 0) {
      return;
    }

    await batch.commit();
    logInfo('auto-created memorial ritual milestones', {
      clanId,
      memberId,
      writeCount,
      preset: AUTO_RITUAL_PRESET,
    });
  },
);

function buildRitualMilestones({
  deathDate,
  gender,
  memberName,
}: {
  deathDate: Date;
  gender: string | null;
  memberName: string;
}): Array<RitualMilestone> {
  const firstMilestoneDays = isMaleGender(gender) ? 50 : 49;
  const firstMilestone = firstMilestoneDays === 50
    ? {
        key: 'first_50_days',
        title: `Lễ 50 ngày - ${memberName}`,
        startsAt: addDays(deathDate, 50),
      }
    : {
        key: 'first_49_days',
        title: `Lễ 49 ngày - ${memberName}`,
        startsAt: addDays(deathDate, 49),
      };

  return [
    firstMilestone,
    {
      key: 'day_100',
      title: `Lễ 100 ngày - ${memberName}`,
      startsAt: addDays(deathDate, 100),
    },
    {
      key: 'year_1',
      title: `Giỗ đầu (1 năm) - ${memberName}`,
      startsAt: addYearsSafely(deathDate, 1),
    },
    {
      key: 'year_2',
      title: `Giỗ hết (2 năm) - ${memberName}`,
      startsAt: addYearsSafely(deathDate, 2),
    },
  ];
}

function buildDescription({
  milestoneTitle,
  deathDate,
}: {
  milestoneTitle: string;
  deathDate: Date;
}): string {
  return `${milestoneTitle}. Tạo tự động từ ngày mất ${formatDateOnly(deathDate)}.`;
}

function eventIdFor(memberId: string, milestoneKey: string): string {
  return `auto_memorial_${memberId}_${milestoneKey}`;
}

function parseDateOnly(value: string | null | undefined): Date | null {
  const normalized = normalizeString(value);
  if (normalized.length === 0) {
    return null;
  }

  const dateOnlyMatch = /^(\d{4})-(\d{2})-(\d{2})$/.exec(normalized);
  if (dateOnlyMatch != null) {
    const year = Number.parseInt(dateOnlyMatch[1] ?? '', 10);
    const month = Number.parseInt(dateOnlyMatch[2] ?? '', 10);
    const day = Number.parseInt(dateOnlyMatch[3] ?? '', 10);
    if (!isValidDateParts(year, month, day)) {
      return null;
    }
    return new Date(Date.UTC(year, month - 1, day));
  }

  const parsed = new Date(normalized);
  if (Number.isNaN(parsed.getTime())) {
    return null;
  }
  return new Date(Date.UTC(parsed.getUTCFullYear(), parsed.getUTCMonth(), parsed.getUTCDate()));
}

function addDays(baseDate: Date, days: number): Date {
  const shifted = new Date(
    Date.UTC(
      baseDate.getUTCFullYear(),
      baseDate.getUTCMonth(),
      baseDate.getUTCDate() + days,
    ),
  );
  return atNineAmClanTimezone(shifted);
}

function addYearsSafely(baseDate: Date, years: number): Date {
  const targetYear = baseDate.getUTCFullYear() + years;
  const month = baseDate.getUTCMonth() + 1;
  const day = baseDate.getUTCDate();

  const candidate = new Date(Date.UTC(targetYear, month - 1, day));
  if (candidate.getUTCMonth() === month - 1 && candidate.getUTCDate() === day) {
    return atNineAmClanTimezone(candidate);
  }

  const monthEnd = new Date(Date.UTC(targetYear, month, 0));
  return atNineAmClanTimezone(monthEnd);
}

function atNineAmClanTimezone(date: Date): Date {
  const offsetHours = timezoneOffsetHours(APP_TIMEZONE);
  return new Date(
    Date.UTC(
      date.getUTCFullYear(),
      date.getUTCMonth(),
      date.getUTCDate(),
      9 - offsetHours,
      0,
      0,
    ),
  );
}

function timezoneOffsetHours(timezone: string): number {
  const normalized = timezone.trim();
  if (normalized === 'Asia/Ho_Chi_Minh') {
    return 7;
  }
  return 0;
}

function isMaleGender(gender: string | null): boolean {
  const normalized = normalizeString(gender).toLowerCase();
  return normalized === 'male' || normalized === 'nam' || normalized === 'm';
}

function isSameCalendarDate(left: Date, right: Date): boolean {
  return (
    left.getUTCFullYear() === right.getUTCFullYear() &&
    left.getUTCMonth() === right.getUTCMonth() &&
    left.getUTCDate() === right.getUTCDate()
  );
}

function isValidDateParts(year: number, month: number, day: number): boolean {
  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) {
    return false;
  }
  if (month < 1 || month > 12 || day < 1 || day > 31) {
    return false;
  }

  const probe = new Date(Date.UTC(year, month - 1, day));
  return (
    probe.getUTCFullYear() === year &&
    probe.getUTCMonth() === month - 1 &&
    probe.getUTCDate() === day
  );
}

function formatDateOnly(date: Date): string {
  const year = `${date.getUTCFullYear()}`.padStart(4, '0');
  const month = `${date.getUTCMonth() + 1}`.padStart(2, '0');
  const day = `${date.getUTCDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function normalizeString(value: unknown): string {
  if (typeof value !== 'string') {
    return '';
  }
  return value.trim();
}

function normalizeNullableString(value: unknown): string | null {
  const normalized = normalizeString(value);
  return normalized.length === 0 ? null : normalized;
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (value == null || typeof value !== 'object') {
    return null;
  }
  return value as Record<string, unknown>;
}
